#配置数据源
spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aotoExcute?characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
    #mysql新版驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    #连接池配置
  druid:
    #初始化大小、最小空闲、最大激活
    initial-size: 5
    min-idle: 5
    max-active: 20
    #配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 合并多个DruidDataSource的监控数据
    use-global-data-source-stat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    #thymeleaf start
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html
#mybatis相关配置
mybatis:
  #当mybatis的xml文件和mapper接口不在相同包下时
  #需要用mapperLocations属性指定xml文件的路径。
  #*是个通配符，代表所有的文件，**代表所有目录下
  mapper-locations: classpath:mapper/*.xml
  #指定bean所在包
  #在mapper.xml中可以使用别名而不使用类的全路径名
  type-aliases-package: com.inspur.auto.entity
#通用mapper配置
mapper:
  #mappers 多个接口时逗号隔开
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL

#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  params: count=countSql
  support-methods-arguments: true
#日志级别
logging:
  file: D:/inpsur.log
  config: classpath:logback-spring.xml


#业务属性
GASP:
  url: http://10.22.186.2:9080/gaps-service/jsonTransport
